export const FETCH_CONVERSATION = "FETCH_CONVERSATION";

export const FETCH_CHAT_CONVERSATION = "FETCH_CHAT_CONVERSATION";
export const FETCH_POST_FANPAGE = "FETCH_POST_FANPAGE";
export const FETCH_COMMENT_BYPOST = "FETCH_COMMENT_BYPOST";

export const SEND_FB_MESSAGE = "SEND_FB_MESSAGE";
export const GENERATE_JWT = "GENERATE_JWT";
